### ISSUE TITLE
Mac Safari

### ISSUE THREAD

**Issue by mpelletiervaillant-zz** [Jowens96/saas-website#1]
This looks so good Jenny! 
I only have a few little suggestions on tiny things if you want: 
-Maybe add a gutter to your text so that way on the small screens the text doesn't touch the edges.
-In the Reviews section, I would add a bit of padding to the heading so it can breathe a little more

Other than that, it looks really good!!

**Comment by Jowens96** [comment]
Hey Mélany, thanks for the spacing advice. I've added gutters to all text and also given the review header some breathing room. :)
