### ISSUE TITLE
Opera - Nav bar alignment

### ISSUE THREAD

**Issue by arobillard** [Jowens96/saas-website#3]
There is some inconsistency with the alignment of the navbar options between your pages. Also, on small screens it is spilling out of the navbar.

I have a fix for the spilling out issue:
- remove the height you have from the `<header`
- add a class of `push-0` to the `<ul>` inside of `<nav>`

<img width="506" alt="screen shot 2018-04-26 at 5 12 13 pm" src="https://user-images.githubusercontent.com/22084666/39332432-5cc9c49e-4975-11e8-9a91-96885c540919.png">
<img width="481" alt="screen shot 2018-04-26 at 5 12 17 pm" src="https://user-images.githubusercontent.com/22084666/39332433-5cd7d142-4975-11e8-87e3-862caddd340e.png">
<img width="301" alt="screen shot 2018-04-26 at 5 12 47 pm" src="https://user-images.githubusercontent.com/22084666/39332434-5cea964c-4975-11e8-8139-96be8890e87b.png">

**Comment by Jowens96** [comment]
Hey Adam, the fix seems to have resolved both problems. Thanks!
