### ISSUE TITLE
Opera ISO Mobile

### ISSUE THREAD

**Issue by jiannanolan** [Jowens96/saas-website#5]
Nav might benefit from bottom padding. "Details about our tried and tested program gets cut off at small screen sizes. Might add gutter to quotes on Tour page.

**Comment by Jowens96** [comment]
Hi Jianna, I've added some more padding to the navigation. I've removed text-center from "details about our tried and tested program" so that it will not be cut off. There is now a gutter on the review text as well. Thanks for the feedback.
